apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd-service
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      # Synology NFS uses all_squash → maps every UID to 1024 on disk.
      securityContext:
        runAsUser: 1024
        runAsGroup: 100
      initContainers:
        - name: init-etcd-data
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/etcd
              chmod 700 /var/lib/etcd
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib
      containers:
        - name: etcd
          image: registry.k8s.io/etcd:3.5.16-0
          command:
            - etcd
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd-service:2379
          ports:
            - containerPort: 2379
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: synology-nfs-ephemeral
        resources:
          requests:
            storage: 2Gi
