apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openclaw-helm
  namespace: default
spec:
  interval: 1h
  url: https://serhanekicii.github.io/openclaw-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: openclaw
      version: "1.3.10"
      sourceRef:
        kind: HelmRepository
        name: openclaw-helm
  values:
    app-template:
      openclawVersion: "latest"
      configMode: merge

      defaultPodOptions:
        securityContext:
          fsGroup: 100
          fsGroupChangePolicy: OnRootMismatch

      controllers:
        main:
          containers:
            main:
              securityContext:
                runAsUser: 1024
                runAsGroup: 100
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              env:
                LITELLM_API_KEY:
                  valueFrom:
                    secretKeyRef:
                      name: litellm-master-key
                      key: credential
                OPENCLAW_GATEWAY_TOKEN:
                  valueFrom:
                    secretKeyRef:
                      name: openclaw
                      key: credential
            chromium:
              securityContext:
                runAsUser: 1024
                runAsGroup: 100
          initContainers:
            init-config:
              securityContext:
                runAsUser: 1024
                runAsGroup: 100
            init-skills:
              securityContext:
                runAsUser: 1024
                runAsGroup: 100

      service:
        main:
          type: NodePort
          ports:
            http:
              port: 18789
              nodePort: 30180

      configMaps:
        config:
          data:
            openclaw.json: |
              {
                "models": {
                  "providers": {
                    "litellm": {
                      "baseUrl": "http://litellm-service:4000",
                      "apiKey": "${LITELLM_API_KEY}",
                      "api": "openai-completions",
                      "models": [
                        { "id": "spark/step-3.5-flash", "name": "Step 3.5 Flash", "contextWindow": 131072, "maxTokens": 8192 },
                        { "id": "step-3.5-flash:free", "name": "Step 3.5 Flash", "contextWindow": 131072, "maxTokens": 8192 },
                        { "id": "step-3.5-flash", "name": "Step 3.5 Flash", "contextWindow": 131072, "maxTokens": 8192 },
                        { "id": "glm-5", "name": "GLM 5", "contextWindow": 128000, "maxTokens": 4096 }
                      ]
                    }
                  }
                },
                "gateway": {
                  "port": 18789,
                  "mode": "local",
                  "bind": "lan",
                  "controlUi": {
                    "allowInsecureAuth": true,
                    "dangerouslyDisableDeviceAuth": true
                  }
                },
                "agents": {
                  "defaults": {
                    "model": {
                      "primary": "litellm/spark/step-3.5-flash",
                      "fallbacks": [
                        "litellm/step-3.5-flash:free",
                        "litellm/step-3.5-flash",
                        "litellm/glm-5"
                      ]
                    }
                  }
                }
              }

      persistence:
        data:
          existingClaim: openclaw-data
          advancedMounts:
            main:
              init-config:
                - path: /home/node/.openclaw
                  subPath: .openclaw
              init-skills:
                - path: /home/node/.openclaw
                  subPath: .openclaw
              main:
                - path: /home/node/.openclaw
                  subPath: .openclaw
