apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.5
  share: /volume1/kubernetes
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-ephemeral
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.5
  share: /volume1/kubernetes
