apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword-system
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: onepassword
  values:
    connect:
      create: false
    operator:
      create: true
      serviceAccount:
        create: true
      token:
        name: op-service-account-token
        key: token
