apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-databases
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres to accept connections..."
              until nc -z postgres-service 5432; do
                sleep 2
              done
              echo "Postgres is ready"
      containers:
        - name: create-db
          image: postgres:16
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - -c
            - |
              for db in litellm open_webui; do
                psql -h postgres-service -U postgres -tc \
                  "SELECT 1 FROM pg_database WHERE datname = '$db'" \
                  | grep -q 1 \
                  || psql -h postgres-service -U postgres -c "CREATE DATABASE $db"
                echo "Database $db is ready"
              done
