---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBx87aTwvnbT6q8koKlj3C7L++0LsW6BOgTTam7GOkS8lUvElPuEdPeBhH6hEmogXGRq0BYzw35NWd/ryXEJoy1MtCAg53cT5c4+GzS6DBinTwsNGi3nJhXIWvzchFruUn+peUDpO9NeRFhJWqG8Ijp8jT+dbUySwH1kGTEZFgDmUugYbBQq5XG6LbpiMqwlrodG8cTcynCjJEd44zFd6IfzZimpvnE1/HM/2AQHaK1KSeO5z5ipu5iRhMsTxVAywBUvqkXWHmMeIp3VgLuxijjy8eyB84Es8OVpkdDuk5hvQRsTmaL2lXnuWd3Aa3bK6BbFwUqWoFUvarTkcHCt4EyghKJ8grKzVxGbVNj8XPvf/V0Kp768tJAVBr9JwSu6iL7K5LRRsuHkk5z/FLYSmjYpQk7RQxflWnkEDt8XyFlQ+b9LPz9UhxR6lhY2LQ5B7AoVl3Dkj4LGOJfH4+KJ6b42KeLd+ZxkRMKQJwHmWo3agQezArc9vrreV7xN3v+WvUNnEleSw6QKwLsJDIrkAjxVl7QHVBtZNTqu78Uo/Z/0hFRMRXQPw19VPYR6iHsnSY5+et+ach38bE6IAC2+Wwsql0reg4+57YvkPQoFcG17HHfPTp7sUFszw27EUIMBV6N2jTuoymKCjrYbFr5mzZWAHl3y3J7n1jthmoj+waJBP9digazl6N36KrIQtjMOPVzm/c3uos89vJorM+IxNgFqwIgCgV+wO/NZsQssBK4Kg==
  template:
    metadata:
      name: postgres-credentials
      namespace: default
