apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Synology NFS uses all_squash → maps every UID to 1024 on disk.
      # Postgres checks stat(PGDATA).st_uid == geteuid(), so the container
      # must run as 1024 for the ownership check to pass.
      securityContext:
        runAsUser: 1024
        runAsGroup: 100
      initContainers:
        - name: init-pgdata
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              rm -rf /var/lib/postgresql/data/pgdata/postmaster.pid
              mkdir -p /var/lib/postgresql/data/pgdata
              chmod 700 /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: synology-nfs
        resources:
          requests:
            storage: 10Gi
